import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { isCampoUuid } from "@/utils/campo";

export type CampoOperador = { user_id: string; email: string; activo: boolean; operario_id: string | null; operario_nombre: string | null; operario_activo: boolean | null };
export const campoOperadoresKey = (comercioId?: string | null) => ["campo", comercioId ?? null, "operadores"] as const;
const valid = (v: unknown): v is CampoOperador => typeof v === "object" && v !== null && typeof (v as Record<string, unknown>).user_id === "string" && typeof (v as Record<string, unknown>).email === "string" && typeof (v as Record<string, unknown>).activo === "boolean";
async function assertAdmin(comercioId: string) { const { data: session, error: sessionError } = await supabase.auth.getUser(); if (sessionError || !session.user) throw new Error("Sin acceso"); const { data, error } = await supabase.from("comercio_usuarios").select("rol").eq("comercio_id", comercioId).eq("user_id", session.user.id).eq("activo", true).maybeSingle(); if (error || data?.rol !== "admin") throw new Error("Sin acceso"); }
async function invoke(comercioId: string, payload: Record<string, unknown>) { await assertAdmin(comercioId); const { data, error } = await supabase.functions.invoke<{ success?: boolean; operadores?: unknown; operador?: unknown }>("campo-operadores", { body: { comercio_id: comercioId, ...payload } }); if (error || !data?.success) throw new Error("No se pudo completar la operación."); return data; }
export function useCampoOperadores(comercioId?: string | null, isAdmin = false) { const qc=useQueryClient(); const enabled=isAdmin&&isCampoUuid(comercioId); const query=useQuery({ queryKey: campoOperadoresKey(comercioId), enabled, queryFn: async (): Promise<CampoOperador[]> => { const data=await invoke(comercioId!,{action:"listar"}); if(!Array.isArray(data.operadores)||!data.operadores.every(valid)) throw new Error("No se pudo cargar los operadores."); return data.operadores; } }); const refresh=()=>qc.invalidateQueries({queryKey:campoOperadoresKey(comercioId),exact:true}); const invite=useMutation({mutationFn:async(email:string)=>{const value=email.trim().toLowerCase();if(!value)throw new Error("Ingresá un email.");return invoke(comercioId!,{action:"invitar",email:value});},onSuccess:refresh}); const setActive=useMutation({mutationFn:async({userId,activo}:{userId:string;activo:boolean})=>{if(!isCampoUuid(userId))throw new Error("Usuario no disponible.");return invoke(comercioId!,{action:activo?"activar":"desactivar",user_id:userId});},onSuccess:refresh}); const link=useMutation({mutationFn:async({userId,operarioId}:{userId:string;operarioId:string|null})=>{if(!isCampoUuid(userId)||operarioId!==null&&!isCampoUuid(operarioId))throw new Error("Operador no disponible.");await assertAdmin(comercioId!);const {error}=await supabase.rpc("campo_vincular_operador",{p_comercio_id:comercioId!,p_user_id:userId,p_operario_id:operarioId??undefined});if(error)throw new Error("No se pudo actualizar la vinculación.");},onSuccess:refresh}); return {query,invite,setActive,link}; }
