import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useComercio } from "@/hooks/useComercio";
import { toast } from "@/hooks/use-toast";

export type Extintor = { id: string; cliente_id: string; numero_extintor: string; numero_serie: string; sector: string | null; marca_id: string | null; clase_id: string | null; anio_prueba_hidraulica: number | null; fecha_ultima_recarga: string | null; fecha_proxima_recarga: string | null; fecha_vencimiento: string | null; anio_fabricacion: number | null; cliente: { nombre: string; apellido: string } | null; marca: { nombre: string } | null; clase: { nombre: string } | null };
export function useExtintores() {
  const { comercio } = useComercio(); const qc = useQueryClient(); const key = ["extintores", comercio?.id];
  const query = useQuery({ queryKey: key, enabled: Boolean(comercio?.id), queryFn: async () => { const { data, error } = await (supabase as any).from("extintores").select("*,cliente:clientes(nombre,apellido),marca:extintor_marcas(nombre),clase:extintor_clases(nombre)").eq("comercio_id", comercio!.id).order("fecha_proxima_recarga"); if (error) throw error; return data as Extintor[]; } });
  const marcas = useQuery({ queryKey: ["extintor_marcas", comercio?.id], enabled: Boolean(comercio?.id), queryFn: async () => { const { data, error } = await (supabase as any).from("extintor_marcas").select("*").eq("comercio_id", comercio!.id).order("nombre"); if (error) throw error; return data as { id: string; nombre: string }[]; } });
  const clases = useQuery({ queryKey: ["extintor_clases", comercio?.id], enabled: Boolean(comercio?.id), queryFn: async () => { const { data, error } = await (supabase as any).from("extintor_clases").select("*").eq("comercio_id", comercio!.id).order("nombre"); if (error) throw error; return data as { id: string; nombre: string }[]; } });
  const save = useMutation({ mutationFn: async (item: Partial<Extintor> & { id?: string }) => { const { cliente, marca, clase, ...base } = item as any; const payload: any = { ...base, comercio_id: comercio!.id }; ["marca_id", "clase_id", "sector", "fecha_ultima_recarga", "fecha_proxima_recarga", "fecha_vencimiento"].forEach((field) => { if (payload[field] === "") payload[field] = null; }); ["anio_prueba_hidraulica", "anio_fabricacion"].forEach((field) => { if (payload[field] === "" || payload[field] === undefined) payload[field] = null; else payload[field] = Number(payload[field]); }); const result = item.id ? await (supabase as any).from("extintores").update(payload).eq("id", item.id) : await (supabase as any).from("extintores").insert(payload); if (result.error) throw result.error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: key }); toast({ title: "Extintor guardado" }); }, onError: (error: Error) => toast({ title: "No se pudo guardar el extintor", description: error.message, variant: "destructive" }) });
  const remove = useMutation({ mutationFn: async (id: string) => { const { error } = await (supabase as any).from("extintores").delete().eq("id", id); if (error) throw error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: key }); toast({ title: "Extintor eliminado" }); } });
  const saveCatalogo = useMutation({ mutationFn: async ({ tabla, nombre }: { tabla: "extintor_marcas" | "extintor_clases"; nombre: string }) => { const { error } = await (supabase as any).from(tabla).insert({ comercio_id: comercio!.id, nombre }); if (error) throw error; }, onSuccess: (_, value) => { qc.invalidateQueries({ queryKey: [value.tabla, comercio?.id] }); } });
  const removeCatalogo = useMutation({ mutationFn: async ({ tabla, id }: { tabla: "extintor_marcas" | "extintor_clases"; id: string }) => { const { error } = await (supabase as any).from(tabla).delete().eq("id", id); if (error) throw error; }, onSuccess: (_, value) => qc.invalidateQueries({ queryKey: [value.tabla, comercio?.id] }) });
  return { extintores: query.data || [], isLoading: query.isLoading, marcas: marcas.data || [], clases: clases.data || [], save: save.mutate, remove: remove.mutate, saveCatalogo: saveCatalogo.mutate, removeCatalogo: removeCatalogo.mutate, saving: save.isPending };
}
