import { useMemo, useState } from "react";
import { AlertTriangle, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { useCampoTelemetriaImportar, useCampoTelemetriaReferences } from "@/hooks/useCampoTelemetria";
import { parseCsv, parseGpx, sha256, type TelemetriaMuestra } from "@/utils/campoTelemetriaParser";
import { supabase } from "@/integrations/supabase/client";

const maxBytes=10*1024*1024, maxSamples=10000, batchSize=500;
type Props={comercioId:string; allowed:boolean};
const safeName=(name:string)=>Array.from(name).map((char)=>char==="/"||char==="\\"||char.charCodeAt(0)<32?"_":char).join("").slice(0,255)||"telemetria";
export function CampoTelemetriaImportador({comercioId,allowed}:Props){
  const refs=useCampoTelemetriaReferences(comercioId,allowed), api=useCampoTelemetriaImportar(comercioId,allowed);
  const [maquinariaId,setMaquinariaId]=useState(""),[ordenId,setOrdenId]=useState(""),[parteId,setParteId]=useState(""),[sesionId,setSesionId]=useState("");
  const [samples,setSamples]=useState<TelemetriaMuestra[]>([]),[format,setFormat]=useState<"csv"|"gpx"|null>(null),[name,setName]=useState(""),[hash,setHash]=useState(""),[attemptId,setAttemptId]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[progress,setProgress]=useState<string|null>(null);
  const parts=useMemo(()=>refs.data?.partes.filter(x=>!ordenId||x.orden_id===ordenId)??[],[refs.data?.partes,ordenId]);
  const sessions=useMemo(()=>refs.data?.sesiones.filter(x=>!parteId||x.parte_id===parteId)??[],[refs.data?.sesiones,parteId]);
  const choose=async(file:File|null)=>{setError(null);setSamples([]);setHash("");setAttemptId(null);if(!file)return;if(file.size>maxBytes){setError("El archivo supera el limite de 10 MB.");return;}const guessed=file.name.toLowerCase().endsWith(".gpx")?"gpx":file.name.toLowerCase().endsWith(".csv")?"csv":null;if(!guessed){setError("Selecciona un archivo CSV o GPX.");return;}const parsed=guessed==="csv"?parseCsv(await file.text()):parseGpx(await file.text());if(parsed.errors.length){setError(parsed.errors[0]);return;}if(parsed.samples.length>maxSamples){setError(`El archivo supera el limite de ${maxSamples} muestras.`);return;}setFormat(parsed.format);setSamples(parsed.samples);setName(safeName(file.name));setHash(await sha256(file));setAttemptId(crypto.randomUUID());};
  const submit=async()=>{if(!allowed||!maquinariaId||!format||!samples.length||!hash||!attemptId)return;setError(null);const id=attemptId;try{setProgress("Iniciando importacion...");await api.iniciar.mutateAsync({id,maquinariaId,ordenId:ordenId||null,parteId:parteId||null,sesionGpsId:sesionId||null,formato:format,nombreArchivo:name,hash});const state=await supabase.rpc("campo_telemetria_estado_importacion",{p_importacion_id:id});if(state.error)throw state.error;const progress=state.data as {proxima_secuencia?:number}|null;const start=Math.max(0,(progress?.proxima_secuencia??1)-1);for(let index=start;index<samples.length;index+=batchSize){const batch=samples.slice(index,index+batchSize);setProgress(`Enviando ${Math.min(index+batch.length,samples.length)} de ${samples.length} muestras...`);await api.cargar.mutateAsync({id,samples:batch});}setProgress("Finalizando importacion...");await api.finalizar.mutateAsync({id,cancelar:false});setProgress("Importacion finalizada.");setSamples([]);setHash("");setAttemptId(null);}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo importar. Podés reintentar el mismo archivo.");setProgress(null);}};
  if(!allowed)return null;
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Upload className="h-5 w-5"/>Importar telemetria</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">CSV canónico o GPX. El archivo se analiza localmente y no se almacena ni se sube.</p><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Maquinaria<select className="mt-1 w-full rounded-md border bg-background p-2" value={maquinariaId} onChange={e=>setMaquinariaId(e.target.value)}><option value="">Seleccionar</option>{refs.data?.maquinarias.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label className="text-sm">Orden opcional<select className="mt-1 w-full rounded-md border bg-background p-2" value={ordenId} onChange={e=>{setOrdenId(e.target.value);setParteId("");setSesionId("")}}><option value="">Sin orden</option>{refs.data?.ordenes.map(x=><option key={x.id} value={x.id}>Orden {x.numero}</option>)}</select></label><label className="text-sm">Parte opcional<select className="mt-1 w-full rounded-md border bg-background p-2" value={parteId} onChange={e=>{setParteId(e.target.value);setSesionId("")}}><option value="">Sin parte</option>{parts.map(x=><option key={x.id} value={x.id}>Parte {x.numero}</option>)}</select></label><label className="text-sm">Sesion GPS opcional<select className="mt-1 w-full rounded-md border bg-background p-2" value={sesionId} onChange={e=>setSesionId(e.target.value)} disabled={!parteId}><option value="">Sin sesion</option>{sessions.map(x=><option key={x.id} value={x.id}>Sesion {x.estado}</option>)}</select></label></div><label className="block text-sm">Archivo CSV o GPX<input className="mt-1 block w-full text-sm" type="file" accept=".csv,.gpx,text/csv,application/gpx+xml" onChange={e=>void choose(e.target.files?.[0]??null)}/></label>{error&&<Alert variant="destructive"><AlertTriangle className="h-4 w-4"/><AlertDescription>{error}</AlertDescription></Alert>}{samples.length>0&&<div className="rounded-md border p-3 text-sm"><strong>{samples.length} muestras válidas ({format?.toUpperCase()})</strong><p className="mt-1 text-muted-foreground">Vista previa: {samples.slice(0,3).map(x=>`${x.timestamp}${x.latitude===null?"":" · GPS"}`).join(" | ")}</p></div>}{progress&&<p className="text-sm text-muted-foreground" aria-live="polite">{progress}</p>}<Button disabled={!maquinariaId||!samples.length||api.iniciar.isPending||api.cargar.isPending||api.finalizar.isPending} onClick={()=>void submit()}>Confirmar e importar</Button></CardContent></Card>;
}
