import { useEffect, useState } from "react";
import { Eye, Pencil } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { OrdenLaborLotesList } from "@/components/campo/OrdenLaborLotesList";
import { OrdenLaborForm } from "@/components/campo/OrdenLaborForm";
import { useSetCampoOrdenLaborStatus } from "@/hooks/useCampoOrdenLabores";
import type { CampoOrdenDetail, CampoOrdenLaborListItem, CampoOrdenLaborUnidad } from "@/types/campo";

const unidadLabels: Record<CampoOrdenLaborUnidad, string> = { ha: "Hectáreas", hora: "Horas", km: "Kilómetros", tonelada: "Toneladas", unidad: "Unidades", fijo: "Fijo por lote" };
const unidadLabel = (value: string) => unidadLabels[value as CampoOrdenLaborUnidad] ?? value;

export function OrdenLaboresList({ comercioId, ordenId, hasAccess, isAdmin, orden, labores }: { comercioId: string; ordenId: string; hasAccess: boolean; isAdmin: boolean; orden: CampoOrdenDetail; labores: CampoOrdenLaborListItem[] }) {
  const canWrite = hasAccess && isAdmin && orden.estado === "borrador" && orden.establecimiento?.activo === true;
  const [editLabor, setEditLabor] = useState<CampoOrdenLaborListItem | null>(null), [statusLabor, setStatusLabor] = useState<CampoOrdenLaborListItem | null>(null), [lotsLabor, setLotsLabor] = useState<CampoOrdenLaborListItem | null>(null), [pending, setPending] = useState(false);
  const setStatus = useSetCampoOrdenLaborStatus(comercioId, ordenId, hasAccess, isAdmin, orden, statusLabor);
  useEffect(() => { setEditLabor(null); setStatusLabor(null); setLotsLabor(null); setPending(false); }, [comercioId, hasAccess, ordenId]);
  const actions = (labor: CampoOrdenLaborListItem) => <div className="flex items-center justify-end gap-3">
    {canWrite && <Button type="button" size="icon" variant="outline" onClick={() => setEditLabor(labor)} aria-label={`Editar labor ${labor.nombre}`} title="Editar labor"><Pencil className="h-4 w-4" /></Button>}
    {canWrite && <Switch checked={labor.activo} onCheckedChange={() => setStatusLabor(labor)} disabled={setStatus.isPending} aria-label={`${labor.activo ? "Desactivar" : "Reactivar"} labor ${labor.nombre}`} />}
    <Button type="button" size="icon" variant="outline" onClick={() => setLotsLabor(labor)} aria-label={`Ver lotes asignados de ${labor.nombre}`} title="Ver lotes asignados"><Eye className="h-4 w-4" /></Button>
  </div>;
  const confirmStatus = async () => { if (!statusLabor || setStatus.isPending) return; try { await setStatus.mutateAsync({ laborId: statusLabor.id, nuevoEstado: !statusLabor.activo }); setStatusLabor(null); } catch { /* conserva confirmación */ } };
  if (!labores.length) return <p className="py-8 text-center text-muted-foreground">Esta orden todavía no tiene labores.</p>;
  return <>
    <div className="grid gap-4 md:hidden">{labores.map((labor) => <Card key={labor.id}><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><CardTitle className="text-base">{labor.nombre}</CardTitle><Badge variant={labor.activo ? "default" : "secondary"}>{labor.activo ? "Activa" : "Inactiva"}</Badge></div></CardHeader><CardContent className="grid grid-cols-2 gap-3 text-sm"><div><span className="block text-muted-foreground">Código</span>{labor.codigo_interno || "Sin código"}</div><div><span className="block text-muted-foreground">Unidad</span>{unidadLabel(labor.unidad)}</div><div><span className="block text-muted-foreground">Posición</span>{labor.posicion}</div><div className="col-span-2"><span className="block text-muted-foreground">Descripción</span><p className="whitespace-pre-wrap">{labor.descripcion || "Sin descripción"}</p></div><div className="col-span-2">{actions(labor)}</div></CardContent></Card>)}</div>
    <div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow><TableHead>Posición</TableHead><TableHead>Nombre</TableHead><TableHead>Código</TableHead><TableHead>Unidad</TableHead><TableHead>Descripción</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{labores.map((labor) => <TableRow key={labor.id}><TableCell>{labor.posicion}</TableCell><TableCell className="font-medium">{labor.nombre}</TableCell><TableCell>{labor.codigo_interno || "Sin código"}</TableCell><TableCell>{unidadLabel(labor.unidad)}</TableCell><TableCell className="max-w-sm whitespace-pre-wrap">{labor.descripcion || "Sin descripción"}</TableCell><TableCell><Badge variant={labor.activo ? "default" : "secondary"}>{labor.activo ? "Activa" : "Inactiva"}</Badge></TableCell><TableCell>{actions(labor)}</TableCell></TableRow>)}</TableBody></Table></div>
    {canWrite && editLabor && <Dialog open onOpenChange={(open) => { if (!open && !pending) setEditLabor(null); }}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto" onEscapeKeyDown={(event) => { if (pending) event.preventDefault(); }} onInteractOutside={(event) => { if (pending) event.preventDefault(); }}><DialogHeader><DialogTitle>Editar labor</DialogTitle></DialogHeader><OrdenLaborForm key={editLabor.id} mode="edit" comercioId={comercioId} ordenId={ordenId} hasAccess={hasAccess} isAdmin={isAdmin} orden={orden} labor={editLabor} onSuccess={() => setEditLabor(null)} onCancel={() => setEditLabor(null)} onSavingChange={setPending} /></DialogContent></Dialog>}
    {lotsLabor && <Dialog open onOpenChange={(open) => { if (!open && !pending) setLotsLabor(null); }}><DialogContent className="max-h-[90vh] max-w-5xl overflow-y-auto" onEscapeKeyDown={(event) => { if (pending) event.preventDefault(); }} onInteractOutside={(event) => { if (pending) event.preventDefault(); }}><DialogHeader><DialogTitle>Lotes asignados · {lotsLabor.nombre}</DialogTitle></DialogHeader><div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground"><span>{lotsLabor.codigo_interno || "Sin código"}</span><span>·</span><span>{unidadLabel(lotsLabor.unidad)}</span><Badge variant={lotsLabor.activo ? "default" : "secondary"}>{lotsLabor.activo ? "Activa" : "Inactiva"}</Badge></div><OrdenLaborLotesList comercioId={comercioId} ordenId={ordenId} hasAccess={hasAccess} isAdmin={isAdmin} orden={orden} labor={lotsLabor} onPendingChange={setPending} /></DialogContent></Dialog>}
    {canWrite && statusLabor && <AlertDialog open onOpenChange={(open) => { if (!open && !setStatus.isPending) setStatusLabor(null); }}><AlertDialogContent onEscapeKeyDown={(event) => { if (setStatus.isPending) event.preventDefault(); }} onInteractOutside={(event) => { if (setStatus.isPending) event.preventDefault(); }}><AlertDialogHeader><AlertDialogTitle>{statusLabor.activo ? "Desactivar labor" : "Reactivar labor"}</AlertDialogTitle><AlertDialogDescription>{statusLabor.activo ? "¿Desactivar esta labor? Sus asignaciones permanecerán guardadas." : "¿Reactivar esta labor?"}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={setStatus.isPending}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={setStatus.isPending} onClick={(event) => { event.preventDefault(); void confirmStatus(); }}>{setStatus.isPending ? "Guardando..." : "Confirmar"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
  </>;
}
