import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Eye } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ParteForm } from "./ParteForm";
import { CampoParteBadge, ParteLifecycleDetails } from "./CampoParteStatus";
import { useCreateCampoParte } from "@/hooks/useCampoPartes";
import { CAMPO_PARTE_ESTADOS, CAMPO_PARTE_ESTADO_LABEL, type CampoOrdenDetail, type CampoOrdenLaborListItem, type CampoParte, type CampoParteEstado } from "@/types/campo";

type Access = { perteneceAlComercio: boolean; isAdmin: boolean; isOperador: boolean; operadorVinculado: boolean; puedeCrearPartes: boolean };
export function PartesList({ comercioId, orden, labores, partes, campoAccess, access, isLoading, hasError }: { comercioId: string; orden: CampoOrdenDetail; labores: CampoOrdenLaborListItem[]; partes: CampoParte[]; campoAccess: Access; access: boolean; isLoading: boolean; hasError: boolean }) {
  const navigate=useNavigate(), [open,setOpen]=useState(false), [saving,setSaving]=useState(false), [estado,setEstado]=useState<CampoParteEstado|"todos">("todos");
  const create=useCreateCampoParte(comercioId,orden.id,access&&campoAccess.puedeCrearPartes,orden,labores);
  const canCreate=access&&campoAccess.puedeCrearPartes&&labores.some(l=>l.activo)&&["planificada","en_progreso"].includes(orden.estado);
  const filtered=useMemo(()=>estado==="todos"?partes:partes.filter(p=>p.estado===estado),[estado,partes]);
  return <Card><div className="flex flex-wrap items-center justify-between gap-3 border-b p-6"><div><h2 className="text-xl font-semibold">Partes de trabajo</h2>{campoAccess.isOperador&&!campoAccess.operadorVinculado&&<p className="mt-2 max-w-xl text-sm text-amber-700">Tu usuario no tiene un operario activo vinculado. Solicitá la vinculación a un administrador.</p>}</div><div className="flex gap-2"><Select value={estado} onValueChange={v=>setEstado(v as CampoParteEstado|"todos")}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todos">Todos</SelectItem>{CAMPO_PARTE_ESTADOS.map(x=><SelectItem key={x} value={x}>{CAMPO_PARTE_ESTADO_LABEL[x]}</SelectItem>)}</SelectContent></Select>{canCreate&&<Button type="button" onClick={()=>setOpen(true)}>Nuevo parte</Button>}</div></div><CardContent className="pt-6">
    {isLoading?<p className="py-8 text-center text-muted-foreground">Cargando partes...</p>:hasError?<p className="py-8 text-center text-destructive">No se pudieron cargar los partes.</p>:filtered.length===0?<p className="py-8 text-center text-muted-foreground">No hay partes para este filtro.</p>:<><div className="grid gap-3 md:hidden">{filtered.map(parte=><Card key={parte.id}><CardContent className="grid grid-cols-2 gap-3 pt-4 text-sm"><div><span className="block text-muted-foreground">Parte</span>N.º {parte.numero}</div><div><span className="block text-muted-foreground">Estado</span><CampoParteBadge estado={parte.estado}/></div><div><span className="block text-muted-foreground">Labor</span>{parte.labor?.nombre??"—"}</div><div><span className="block text-muted-foreground">Fecha</span>{parte.fecha_trabajo}</div><div className="col-span-2"><ParteLifecycleDetails parte={parte}/></div><div className="col-span-2 flex justify-end"><Button type="button" size="icon" variant="outline" onClick={()=>navigate(`/campo/ordenes/${orden.id}/partes/${parte.id}`)} aria-label={`Ver detalle del parte número ${parte.numero}`} title="Ver detalle"><Eye className="h-4 w-4"/></Button></div></CardContent></Card>)}</div><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow><TableHead>N.º</TableHead><TableHead>Labor</TableHead><TableHead>Fecha</TableHead><TableHead>Estado</TableHead><TableHead>Propiedad y aprobación</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{filtered.map(parte=><TableRow key={parte.id}><TableCell>{parte.numero}</TableCell><TableCell>{parte.labor?.nombre??"—"}</TableCell><TableCell>{parte.fecha_trabajo}</TableCell><TableCell><CampoParteBadge estado={parte.estado}/></TableCell><TableCell className="min-w-72"><ParteLifecycleDetails parte={parte}/></TableCell><TableCell className="text-right"><Button type="button" size="icon" variant="outline" onClick={()=>navigate(`/campo/ordenes/${orden.id}/partes/${parte.id}`)} aria-label={`Ver detalle del parte número ${parte.numero}`} title="Ver detalle"><Eye className="h-4 w-4"/></Button></TableCell></TableRow>)}</TableBody></Table></div></>}
    {canCreate&&<Dialog open={open} onOpenChange={v=>{if(!saving)setOpen(v)}}><DialogContent className="max-h-[90vh] overflow-y-auto" onEscapeKeyDown={e=>{if(saving)e.preventDefault()}} onInteractOutside={e=>{if(saving)e.preventDefault()}}><DialogHeader><DialogTitle>Nuevo parte</DialogTitle></DialogHeader><ParteForm labores={labores} pending={create.isPending} onSaving={setSaving} onSubmit={async values=>{await create.mutateAsync(values);setOpen(false)}}/></DialogContent></Dialog>}
  </CardContent></Card>;
}
