import { FormEvent, useMemo, useState } from "react";
import { format } from "date-fns";
import { Eye, Pencil, Plus, ReceiptText, Search, Trash2 } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useActualizarGastoEgreso, useCrearGastoEgreso, useEliminarGastoEgreso, useGastosEgresos } from "@/hooks/useGastosEgresos";
import { CATEGORIAS_GASTO, EstadoGasto, GastoEgreso, MEDIOS_PAGO_GASTO, MedioPagoGasto } from "@/types/gasto";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

const db = supabase as any;
const hoy = format(new Date(), "yyyy-MM-dd");
const currency = (value: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS" }).format(Number(value || 0));

type GastoForm = { fecha: string; categoria: string; concepto: string; monto: number; medioPago: MedioPagoGasto; estado: EstadoGasto; numeroComprobante: string; observaciones: string; cajaId: string };
const initialForm = (): GastoForm => ({ fecha: hoy, categoria: "Otros", concepto: "", monto: 0, medioPago: "transferencia", estado: "pagado", numeroComprobante: "", observaciones: "", cajaId: "" });
const toForm = (gasto: GastoEgreso): GastoForm => ({ fecha: gasto.fecha, categoria: gasto.categoria, concepto: gasto.concepto, monto: Number(gasto.monto), medioPago: gasto.medio_pago, estado: gasto.estado, numeroComprobante: gasto.numero_comprobante || "", observaciones: gasto.observaciones || "", cajaId: gasto.caja_id || "" });

export default function GastosEgresos() {
  const [formOpen, setFormOpen] = useState(false);
  const [detail, setDetail] = useState<GastoEgreso | null>(null);
  const [deleting, setDeleting] = useState<GastoEgreso | null>(null);
  const [editing, setEditing] = useState<GastoEgreso | null>(null);
  const [form, setForm] = useState<GastoForm>(initialForm);
  const [buscar, setBuscar] = useState("");
  const { data: gastos = [], isLoading } = useGastosEgresos();
  const crear = useCrearGastoEgreso(); const actualizar = useActualizarGastoEgreso(); const eliminar = useEliminarGastoEgreso();
  const { data: cajasAbiertas = [] } = useQuery({ queryKey: ["cajas-abiertas"], queryFn: async () => { const { data, error } = await db.from("cajas_diarias").select("id, fecha").eq("estado", "abierta").order("fecha", { ascending: false }); if (error) throw error; return data || []; } });
  const rows = useMemo(() => gastos.filter(g => { const term = buscar.trim().toLowerCase(); return !term || [g.concepto, g.numero_comprobante, g.categoria].filter(Boolean).join(" ").toLowerCase().includes(term); }), [gastos, buscar]);
  const isCashPaid = form.medioPago === "efectivo" && form.estado === "pagado";
  const saving = crear.isPending || actualizar.isPending;
  const set = <K extends keyof GastoForm>(key: K, value: GastoForm[K]) => setForm(current => ({ ...current, [key]: value }));
  const openNew = () => { setEditing(null); setForm(initialForm()); setFormOpen(true); };
  const openEdit = (gasto: GastoEgreso) => { setEditing(gasto); setForm(toForm(gasto)); setFormOpen(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const gasto = { fecha: form.fecha, categoria: form.categoria, concepto: form.concepto, monto: form.monto, medio_pago: form.medioPago, estado: form.estado, caja_id: isCashPaid ? form.cajaId : null, numero_comprobante: form.numeroComprobante || null, observaciones: form.observaciones || null }; if (editing) await actualizar.mutateAsync({ id: editing.id, gasto }); else await crear.mutateAsync(gasto); setFormOpen(false); setEditing(null); };
  const confirmDelete = async () => { if (!deleting) return; await eliminar.mutateAsync(deleting.id); setDeleting(null); };
  const paymentLabel = (gasto: GastoEgreso) => MEDIOS_PAGO_GASTO.find(x => x.value === gasto.medio_pago)?.label || gasto.medio_pago;
  return <div className="p-6"><div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-3xl font-bold">Gastos y egresos</h1><p className="text-muted-foreground">Consultá los gastos registrados y cargá nuevos movimientos cuando sea necesario.</p></div><Button onClick={openNew}><Plus className="mr-2 h-4 w-4" />Nuevo gasto o egreso</Button></div>
    <Dialog open={formOpen} onOpenChange={open => { setFormOpen(open); if (!open) setEditing(null); }}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{editing ? "Editar gasto o egreso" : "Nuevo gasto o egreso"}</DialogTitle></DialogHeader><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
      <Field label="Fecha"><Input type="date" value={form.fecha} onChange={e => set("fecha", e.target.value)} required /></Field><Field label="Categoría"><Select value={form.categoria} onValueChange={value => set("categoria", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{CATEGORIAS_GASTO.map(x => <SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field>
      <Field label="Concepto"><Input value={form.concepto} onChange={e => set("concepto", e.target.value)} required /></Field><Field label="Importe"><Input type="number" min="0.01" step="0.01" value={form.monto || ""} onChange={e => set("monto", Number(e.target.value))} required /></Field>
      <Field label="Medio de pago"><Select value={form.medioPago} onValueChange={value => set("medioPago", value as MedioPagoGasto)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{MEDIOS_PAGO_GASTO.map(x => <SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></Field><Field label="Estado"><Select value={form.estado} onValueChange={value => set("estado", value as EstadoGasto)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="pagado">Pagado</SelectItem><SelectItem value="pendiente">Pendiente</SelectItem></SelectContent></Select></Field>
      {isCashPaid && <div className="space-y-2 sm:col-span-2"><Label>Caja abierta</Label><Select value={form.cajaId} onValueChange={value => set("cajaId", value)}><SelectTrigger><SelectValue placeholder="Seleccionar caja" /></SelectTrigger><SelectContent>{cajasAbiertas.map((c: { id: string; fecha: string }) => <SelectItem key={c.id} value={c.id}>Caja del {format(new Date(`${c.fecha}T00:00:00`), "dd/MM/yyyy")}</SelectItem>)}</SelectContent></Select><p className="text-xs text-muted-foreground">Los gastos en efectivo pagados se registran también en la caja seleccionada.</p></div>}
      <Field label="Comprobante"><Input value={form.numeroComprobante} onChange={e => set("numeroComprobante", e.target.value)} placeholder="Nro. factura/ticket" /></Field><div className="space-y-2 sm:col-span-2"><Label>Observaciones</Label><Textarea value={form.observaciones} onChange={e => set("observaciones", e.target.value)} /></div><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={() => setFormOpen(false)}>Cancelar</Button><Button disabled={saving || form.monto <= 0 || (isCashPaid && !form.cajaId)}>{editing ? "Guardar cambios" : "Registrar gasto"}</Button></div>
    </form></DialogContent></Dialog>
    <Card><CardContent className="pt-6"><div className="relative max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={buscar} onChange={e => setBuscar(e.target.value)} placeholder="Filtrar por concepto, categoría o comprobante..." /></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Gastos y egresos</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Concepto</TableHead><TableHead>Categoría</TableHead><TableHead>Pago</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Importe</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{isLoading ? <TableRow><TableCell colSpan={7}>Cargando...</TableCell></TableRow> : rows.length === 0 ? <TableRow><TableCell colSpan={7} className="py-10 text-center text-muted-foreground"><ReceiptText className="mx-auto mb-2 h-6 w-6" />No se encontraron gastos con esos filtros.</TableCell></TableRow> : rows.map(g => <TableRow key={g.id}><TableCell>{format(new Date(`${g.fecha}T00:00:00`), "dd/MM/yyyy")}</TableCell><TableCell><div className="font-medium">{g.concepto}</div>{g.numero_comprobante && <div className="text-xs text-muted-foreground">Comp. {g.numero_comprobante}</div>}</TableCell><TableCell>{g.categoria}</TableCell><TableCell>{paymentLabel(g)}</TableCell><TableCell><Badge variant={g.estado === "pagado" ? "default" : "secondary"}>{g.estado}</Badge></TableCell><TableCell className="text-right font-medium">{currency(g.monto)}</TableCell><TableCell><div className="flex justify-end gap-2"><Button type="button" size="icon" variant="outline" onClick={() => setDetail(g)} aria-label={`Ver detalle de ${g.concepto}`} title="Ver detalle"><Eye className="h-4 w-4" /></Button><Button type="button" size="icon" variant="outline" onClick={() => openEdit(g)} aria-label={`Editar ${g.concepto}`} title="Editar"><Pencil className="h-4 w-4" /></Button><Button type="button" size="icon" variant="destructive" onClick={() => setDeleting(g)} aria-label={`Eliminar ${g.concepto}`} title="Eliminar"><Trash2 className="h-4 w-4" /></Button></div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Dialog open={Boolean(detail)} onOpenChange={open => !open && setDetail(null)}><DialogContent className="max-w-4xl"><DialogHeader><DialogTitle>Detalle del gasto</DialogTitle></DialogHeader>{detail && <div className="space-y-4 text-sm"><div className="grid grid-cols-1 gap-x-10 gap-y-2 sm:grid-cols-2 lg:grid-cols-4"><p><strong>Fecha:</strong> {format(new Date(`${detail.fecha}T00:00:00`), "dd/MM/yyyy")}</p><p><strong>Estado:</strong> <Badge className="ml-1" variant={detail.estado === "pagado" ? "default" : "secondary"}>{detail.estado}</Badge></p><p><strong>Importe:</strong> {currency(detail.monto)}</p><p><strong>Comprobante:</strong> {detail.numero_comprobante || "-"}</p></div><div><h4 className="mb-2 font-semibold">Información del gasto</h4><Table><TableHeader><TableRow><TableHead>Concepto</TableHead><TableHead>Categoría</TableHead><TableHead>Medio de pago</TableHead><TableHead>Observaciones</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell className="font-medium">{detail.concepto}</TableCell><TableCell>{detail.categoria}</TableCell><TableCell>{paymentLabel(detail)}</TableCell><TableCell>{detail.observaciones || "-"}</TableCell></TableRow></TableBody></Table></div></div>}</DialogContent></Dialog>
    <AlertDialog open={Boolean(deleting)} onOpenChange={open => !open && setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Eliminar gasto o egreso</AlertDialogTitle><AlertDialogDescription>Vas a eliminar “{deleting?.concepto}”. Esta acción no se puede deshacer{deleting?.medio_pago === "efectivo" && deleting.estado === "pagado" ? " y quitará su movimiento asociado de Caja diaria." : "."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={confirmDelete} disabled={eliminar.isPending}>Eliminar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
