import { ChangeEvent, useEffect, useState } from "react";
import { ImagePlus, Trash2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useComercio } from "@/hooks/useComercio";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
type Slide={id:string;imagen_path:string;titulo:string;subtitulo:string;enlace:string|null;orden:number;publicado:boolean};
export default function TiendaOnline(){
 const {comercio}=useComercio(),[slides,setSlides]=useState<Slide[]>([]),[loading,setLoading]=useState(false),[config,setConfig]=useState<any>({banner:{activo:false,texto:"",enlace:"",imagen_path:""},identidad:{color_primario:"#111827",color_acento:"#d65e37",titulo_portada:""},contacto:{instagram:"",facebook:"",horarios:""},envios:{condiciones:""},ayuda:{cambios:"",pagos:"",preguntas:""}});
 const load=async()=>{if(!comercio) return;const [{data},{data:settings}]=await Promise.all([(supabase as any).from("tienda_landing_slides").select("*").eq("comercio_id",comercio.id).order("orden"),(supabase as any).from("tienda_configuraciones").select("contenido").eq("comercio_id",comercio.id).maybeSingle()]);setSlides(data||[]);if(settings?.contenido)setConfig((v:any)=>({...v,...settings.contenido,banner:{...v.banner,...settings.contenido.banner},identidad:{...v.identidad,...settings.contenido.identidad},contacto:{...v.contacto,...settings.contenido.contacto},envios:{...v.envios,...settings.contenido.envios},ayuda:{...v.ayuda,...settings.contenido.ayuda}}))};
 useEffect(()=>{void load()},[comercio?.id]);
 const save=async(slide:Slide)=>{await (supabase as any).from("tienda_landing_slides").update({titulo:slide.titulo,subtitulo:slide.subtitulo,enlace:slide.enlace||null,orden:slide.orden,publicado:slide.publicado}).eq("id",slide.id);void load()};
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!comercio)return;setLoading(true);const ext=file.name.split(".").pop()||"jpg",path=`${comercio.id}/landing/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from("tienda-landing").upload(path,file,{upsert:false});if(!error)await (supabase as any).from("tienda_landing_slides").insert({comercio_id:comercio.id,imagen_path:path,orden:slides.length+1,titulo:"Nueva colección",subtitulo:""});setLoading(false);void load();e.target.value=""};
 const remove=async(s:Slide)=>{if(!confirm("¿Eliminar esta imagen del slider?"))return;await supabase.storage.from("tienda-landing").remove([s.imagen_path]);await (supabase as any).from("tienda_landing_slides").delete().eq("id",s.id);void load()};
 const set=(group:string,key:string,value:any)=>setConfig((current:any)=>({...current,[group]:{...current[group],[key]:value}}));
 const saveConfig=async()=>{if(!comercio)return;setLoading(true);await (supabase as any).from("tienda_configuraciones").upsert({comercio_id:comercio.id,contenido:config});setLoading(false)};
 const url=(p:string)=>supabase.storage.from("tienda-landing").getPublicUrl(p).data.publicUrl;
 if(!comercio)return <div className="p-8">Seleccioná un comercio para configurar su tienda.</div>;
 return <div className="container mx-auto max-w-5xl space-y-6 p-6"><div><h1 className="text-3xl font-bold">Tienda online</h1><p className="text-muted-foreground">Administrá la portada y la información pública de {comercio.nombre_comercio}.</p></div><Card><CardHeader><CardTitle>Slider de portada</CardTitle></CardHeader><CardContent className="space-y-5"><Label className="flex w-fit cursor-pointer items-center gap-2"><Button type="button" disabled={loading} asChild><span><ImagePlus className="mr-2 h-4 w-4"/>{loading?"Cargando...":"Cargar imagen"}</span></Button><Input className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></Label><p className="text-sm text-muted-foreground">JPG, PNG o WebP, hasta 5 MB. Recomendado: 1920 × 750 px.</p><div className="space-y-4">{slides.map(s=><div key={s.id} className="grid gap-4 rounded-lg border p-4 md:grid-cols-[190px_1fr]"><img className="h-28 w-full rounded object-cover" src={url(s.imagen_path)} alt=""/><div className="grid gap-3"><Input value={s.titulo} placeholder="Título" onChange={e=>setSlides(v=>v.map(x=>x.id===s.id?{...x,titulo:e.target.value}:x))}/><Input value={s.subtitulo} placeholder="Texto" onChange={e=>setSlides(v=>v.map(x=>x.id===s.id?{...x,subtitulo:e.target.value}:x))}/><Input value={s.enlace||""} placeholder="Enlace opcional" onChange={e=>setSlides(v=>v.map(x=>x.id===s.id?{...x,enlace:e.target.value}:x))}/><div className="flex items-center gap-3"><Label>Orden <Input className="ml-2 inline w-16" type="number" min="1" value={s.orden} onChange={e=>setSlides(v=>v.map(x=>x.id===s.id?{...x,orden:Number(e.target.value)}:x))}/></Label><Switch checked={s.publicado} onCheckedChange={v=>setSlides(x=>x.map(y=>y.id===s.id?{...y,publicado:v}:y))}/><span className="text-sm">Publicado</span><Button size="sm" onClick={()=>save(s)}>Guardar</Button><Button size="icon" variant="destructive" onClick={()=>remove(s)}><Trash2 className="h-4 w-4"/></Button></div></div></div>)}</div></CardContent></Card></div>;
}
