export type ModuleHelp = {
  title: string;
  summary: string;
  purpose: string;
  features: string[];
  steps: string[];
  tips: string[];
};

type HelpRoute = { prefixes: string[]; help: ModuleHelp };

const help = (
  title: string,
  summary: string,
  purpose: string,
  features: string[],
  steps: string[],
  tips: string[],
): ModuleHelp => ({ title, summary, purpose, features, steps, tips });

const routes: HelpRoute[] = [
  { prefixes: ["/campo/operarios"], help: help("Operarios", "Administrá el catálogo de operarios del comercio activo.", "Permite buscar, crear, editar, desactivar y reactivar operarios según tus permisos.", ["Buscar por datos identificatorios.", "Filtrar por estado.", "Gestionar desde celular o escritorio."], ["Elegí Operarios en Vortex Campo.", "Usá el buscador o filtro.", "Gestioná registros si sos administrador."], ["La vinculación con usuarios se incorporará más adelante.", "RLS protege los datos del comercio."]) },
  { prefixes: ["/campo/maquinarias"], help: help("Maquinarias", "Administrá las maquinarias del comercio activo.", "Permite mantener identificación y datos técnicos.", ["Buscar y filtrar maquinarias.", "Crear y editar datos técnicos.", "Desactivar sin eliminar historial."], ["Elegí Maquinarias en Vortex Campo.", "Localizá el equipo.", "Usá las acciones disponibles según tu rol."], ["No se eliminan registros.", "RLS protege los datos del comercio."]) },
  { prefixes: ["/campo/insumos"], help: help("Insumos", "Administrá los insumos del comercio activo.", "Permite mantener nombres, códigos y unidades operativas.", ["Buscar y filtrar insumos.", "Crear y editar unidades.", "Desactivar sin eliminar historial."], ["Elegí Insumos en Vortex Campo.", "Localizá el insumo.", "Usá las acciones disponibles según tu rol."], ["Cambiar una unidad no altera partes confirmados.", "RLS protege los datos del comercio."]) },
  { prefixes: ["/campo/ordenes"], help: help("Órdenes de trabajo", "Consultá la planificación del comercio activo.", "Esta etapa permite revisar las órdenes de trabajo y sus datos principales sin realizar cambios.", ["Buscar por número, código, cliente, establecimiento o descripción.", "Filtrar órdenes por estado.", "Consultar fechas planificadas desde celular o escritorio."], ["Ingresá a Vortex Campo y elegí Órdenes de trabajo.", "Usá el buscador o el filtro de estado.", "Revisá el cliente, establecimiento y rango de fechas."], ["La creación y edición se incorporarán en fases posteriores.", "El acceso continúa protegido por membresía y RLS."]) },
  { prefixes: ["/campo"], help: help("Vortex Campo", "Consultá los establecimientos rurales del comercio activo.", "Esta primera etapa ofrece una vista de solo lectura de los establecimientos asociados al comercio y sus clientes.", ["Buscar establecimientos por nombre, código, cliente o localidad.", "Filtrar registros activos e inactivos.", "Consultar superficie y estado desde celular o escritorio."], ["Ingresá a Vortex Campo desde el menú lateral.", "Usá el buscador o el filtro de estado para localizar un establecimiento.", "Verificá el cliente y la superficie informados."], ["La creación, edición y consulta de lotes se incorporarán en etapas posteriores.", "El acceso a los datos continúa protegido por las políticas RLS."]) },
  { prefixes: ["/mercado-pago"], help: help("Mercado Pago", "Conectá la cuenta del comercio y administrá cobros online y presenciales.", "Este módulo vincula la cuenta de Mercado Pago propia del comercio mediante autorización segura. Permite habilitar Checkout Pro para la tienda online, crear sucursales y cajas para cobros QR y consultar el estado de cada operación sin compartir credenciales privadas.", ["Conectar o desconectar la cuenta Mercado Pago del comercio.", "Habilitar Checkout Pro para pedidos de la tienda online.", "Habilitar cobros presenciales mediante QR dinámico, estático o híbrido.", "Crear sucursales y cajas vinculadas a Mercado Pago.", "Consultar importes, referencias y estados de las últimas operaciones.", "Cancelar, sincronizar o devolver operaciones cuando corresponda."], ["Presioná Conectar cuenta de Mercado Pago e iniciá sesión con la cuenta del comercio.", "Autorizá a Vortex y comprobá que la cuenta aparezca como Conectada.", "Trabajá primero en ambiente de pruebas y elegí las funciones que utilizará el comercio.", "Si vas a cobrar con QR, creá la sucursal y la caja antes de generar la primera orden.", "Guardá la configuración y realizá una operación de prueba.", "Verificá que el pago figure como aprobado en Mercado Pago y en Vortex antes de entregar la mercadería."], ["Cada comercio debe conectar su propia cuenta: el dinero se acredita directamente en esa cuenta.", "Generar un QR o regresar desde Checkout no confirma el cobro; esperá el estado Aprobado informado por Mercado Pago.", "No compartas Access Tokens, Client Secrets ni claves de webhook.", "Los pedidos con envío deben abonarse cuando el costo final esté definido.", "No repitas una operación pendiente: actualizá su estado para evitar cobros duplicados."]) },
  { prefixes: ["/caja"], help: help("Caja diaria", "Controlá la apertura, los movimientos y el cierre de cada jornada.", "Este módulo concentra el dinero que ingresa y egresa del comercio. Permite comparar el saldo esperado con el importe informado al cerrar y conserva la trazabilidad de cada diferencia. Para los cobros con tarjeta muestra también el bruto cobrado, las comisiones estimadas y el neto esperado a acreditar.", ["Abrir la caja indicando el monto inicial.", "Registrar ingresos y egresos con concepto y observaciones.", "Consultar ventas y movimientos vinculados a la jornada.", "Revisar el bruto cobrado con tarjetas, la comisión estimada y el neto esperado.", "Cerrar la caja informando el efectivo contado.", "Acceder desde el resumen al módulo de conciliación de tarjetas."], ["Seleccioná la fecha de trabajo.", "Abrí la caja antes de comenzar a registrar movimientos.", "Cargá cada ingreso o egreso no generado automáticamente.", "Revisá el resumen de medios de pago y el neto estimado de tarjetas.", "Usá el acceso a conciliación para controlar las acreditaciones.", "Cerrá la caja y confirmá el importe final."], ["La comisión de tarjeta no reduce el efectivo físico esperado en caja.", "No uses un egreso para representar una comisión: se controla desde Tarjetas.", "No uses un egreso para corregir una venta: corregí la operación de origen.", "Revisá las diferencias antes de confirmar el cierre."]) },
  { prefixes: ["/ventas"], help: help("Ventas", "Registrá ventas, cobros y comprobantes desde un único flujo.", "El módulo permite crear y administrar las operaciones comerciales. Cada venta conserva cliente, productos, cantidades, precios, impuestos, descuentos, recargos y medios de pago.", ["Crear ventas a consumidor final o clientes registrados.", "Combinar efectivo, transferencia, tarjeta, cheque y cuenta corriente.", "Aplicar descuentos o recargos.", "Consultar, editar e imprimir comprobantes.", "Registrar facturas y recibos según la configuración habilitada."], ["Presioná Nueva venta.", "Elegí el cliente y agregá los productos.", "Verificá cantidades, precios y totales.", "Seleccioná uno o varios medios de pago.", "Confirmá la operación y emití el comprobante."], ["Comprobá el cliente antes de usar cuenta corriente.", "Una venta fiscal autorizada puede tener restricciones de edición.", "Usá el buscador para localizar comprobantes por número o cliente."]) },
  { prefixes: ["/presupuestos"], help: help("Presupuestos", "Prepará propuestas comerciales y convertí las aprobadas en ventas.", "Los presupuestos permiten cotizar productos sin afectar caja ni stock como una venta definitiva. Conservan precios, cantidades y condiciones para continuar luego el circuito comercial.", ["Crear, editar e imprimir presupuestos.", "Asignar cliente, productos, descuentos y recargos.", "Consultar propuestas anteriores.", "Convertir un presupuesto aceptado en venta.", "Mantener presupuestos separados del historial de ventas."], ["Creá un presupuesto y seleccioná el cliente.", "Agregá productos y revisá las condiciones.", "Guardalo e imprimilo para compartir.", "Cuando sea aceptado, utilizá la acción de conversión a venta.", "Completá el medio de pago en la venta resultante."], ["Revisá la vigencia de precios antes de convertir presupuestos antiguos.", "La conversión evita volver a cargar productos y cantidades."]) },
  { prefixes: ["/productos"], help: help("Productos", "Administrá catálogo, precios, clasificación y existencias.", "Centraliza la información utilizada en ventas: códigos, descripción, costos, utilidad, IVA, moneda, stock, proveedor, rubro, subrubro y marca.", ["Crear y editar productos.", "Buscar por código, descripción o código de barras.", "Gestionar marcas, rubros y subrubros.", "Trabajar con precios en pesos o dólares.", "Imprimir listados y etiquetas según las opciones disponibles."], ["Definí previamente rubros, marcas y proveedores si los necesitás.", "Creá el producto con un código único.", "Cargá costo, utilidad, impuestos y moneda.", "Asigná la clasificación y el stock inicial.", "Revisá el precio de venta calculado antes de guardar."], ["Evitá reutilizar códigos de productos diferentes.", "Mantené actualizado el costo para que la utilidad sea representativa.", "Los productos sin stock se identifican también desde los reportes."]) },
  { prefixes: ["/clientes"], help: help("Clientes", "Concentrá datos comerciales, fiscales e historial de cada cliente.", "El módulo organiza personas físicas y jurídicas, sus datos de contacto, condición fiscal y domicilio. Se relaciona con ventas, presupuestos y cuentas corrientes.", ["Crear, editar, buscar y consultar clientes.", "Registrar CUIT, email, teléfono y domicilio.", "Diferenciar personas físicas y jurídicas.", "Consultar informes, compras y saldos.", "Eliminar registros cuando no tengan relaciones que lo impidan."], ["Elegí Nuevo cliente.", "Seleccioná el tipo de persona.", "Completá identidad, situación fiscal y contacto.", "Cargá el domicilio principal.", "Guardá y verificá el registro en el listado."], ["Completá correctamente el CUIT antes de emitir comprobantes fiscales.", "Consultá el informe del cliente para revisar ventas y deuda."]) },
  { prefixes: ["/proveedores"], help: help("Proveedores", "Organizá los datos comerciales y fiscales de tus proveedores.", "Permite mantener una agenda centralizada de proveedores para relacionarlos con productos y facilitar consultas administrativas.", ["Crear y editar proveedores.", "Registrar CUIT, razón social y situación fiscal.", "Guardar información de contacto y domicilio.", "Buscar rápidamente dentro del listado.", "Consultar reportes de personas físicas y jurídicas."], ["Presioná Nuevo proveedor.", "Elegí el tipo de persona y completá sus datos.", "Agregá contacto y domicilio.", "Guardá el proveedor.", "Asignalo a los productos correspondientes."], ["Usá un CUIT válido y evitá duplicar proveedores.", "Actualizar el proveedor no modifica automáticamente datos históricos."]) },
  { prefixes: ["/cuenta-corriente"], help: help("Cuenta corriente", "Controlá débitos, créditos, pagos y saldos por cliente.", "Registra las ventas financiadas y los pagos posteriores. El saldo se calcula a partir de todos los movimientos y permite conocer rápidamente clientes deudores o acreedores.", ["Consultar saldos individuales y generales.", "Registrar pagos, débitos, créditos y ajustes autorizados.", "Vincular movimientos con ventas.", "Ver el historial cronológico de cada cliente.", "Generar e imprimir estados de cuenta."], ["Seleccioná un cliente para abrir su detalle.", "Revisá el saldo y los movimientos anteriores.", "Usá Nuevo movimiento para registrar un pago o ajuste.", "Indicá fecha, tipo, monto y concepto.", "Confirmá y verificá el nuevo saldo."], ["Registrá los pagos con su fecha real.", "No dupliques pagos ya incorporados desde una venta.", "Agregá observaciones que permitan auditar ajustes manuales."]) },
  { prefixes: ["/cheques"], help: help("Cartera de cheques", "Registrá y seguí los cheques recibidos por el comercio.", "Permite controlar cada cheque desde su recepción hasta su depósito, cobro, rechazo u otro cambio de estado, incluyendo banco y vencimiento.", ["Registrar número, banco, emisor e importe.", "Controlar fechas de emisión y vencimiento.", "Consultar el estado de la cartera.", "Editar datos y actualizar estados.", "Relacionar cheques recibidos como forma de pago."], ["Ingresá a Nuevo cheque o registralo desde una venta.", "Completá los datos del documento.", "Verificá especialmente número, monto y vencimiento.", "Guardá el cheque en cartera.", "Actualizá su estado cuando sea depositado o cobrado."], ["Revisá periódicamente los próximos vencimientos.", "No elimines un cheque para representar un cambio de estado."]) },
  { prefixes: ["/bancos"], help: help("Bancos", "Administrá las entidades bancarias utilizadas por el comercio.", "Es un módulo de configuración que provee los bancos disponibles para cheques y otras operaciones relacionadas.", ["Crear y editar bancos.", "Registrar nombre y datos complementarios.", "Buscar entidades existentes.", "Usar bancos en el registro de cheques."], ["Presioná Nuevo banco.", "Completá el nombre y la información disponible.", "Guardá el registro.", "Seleccioná el banco desde los módulos relacionados."], ["Evitá crear variantes duplicadas del mismo banco.", "Revisá las relaciones existentes antes de eliminar."]) },
  { prefixes: ["/tarjetas"], help: help("Tarjetas", "Configurá tarjetas, comisiones, cuotas y conciliaciones.", "Centraliza las condiciones de cobro con tarjeta. La comisión es el porcentaje que la administradora descuenta al comercio, mientras que el recargo de cuotas se cobra al cliente. El sistema calcula silenciosamente comisión estimada = importe cobrado × porcentaje y neto esperado = importe cobrado − comisión. Estos datos son internos y no aparecen en la venta ni en el comprobante del cliente.", ["Crear y editar tarjetas.", "Definir la comisión descontada al comercio.", "Configurar planes de cuotas y sus recargos.", "Congelar automáticamente el porcentaje aplicado en cada pago.", "Consultar importes brutos, comisiones y netos esperados.", "Conciliar una operación individual o varias de una misma tarjeta.", "Registrar neto real, fecha, referencia y observaciones de la liquidación.", "Identificar acreditaciones con diferencias."], ["Creá la tarjeta e indicá su comisión vigente.", "Configurá las cuotas y el recargo que corresponda al cliente.", "Ingresá a la pestaña Conciliación y aplicá filtros de fecha, tarjeta o estado.", "Seleccioná las ventas incluidas en un mismo depósito; deben pertenecer a la misma tarjeta.", "Registrá el neto realmente acreditado, la fecha y la referencia.", "Revisá la diferencia calculada y el estado final de cada operación."], ["No confundas la comisión de la tarjeta con el recargo de cuotas al cliente.", "El porcentaje queda congelado al guardar el pago: cambiar la tarjeta no modifica ventas anteriores.", "En una liquidación agrupada, el neto real se distribuye proporcionalmente entre las operaciones seleccionadas.", "Una diferencia puede corresponder a impuestos, retenciones u otros ajustes de la administradora.", "Los pagos conciliados quedan protegidos para preservar el historial."]) },
  { prefixes: ["/afip"], help: help("ARCA y facturación electrónica", "Configurá la emisión fiscal y consultá comprobantes autorizados.", "Concentra los datos necesarios para emitir comprobantes electrónicos mediante los servicios fiscales habilitados para el comercio.", ["Configurar punto de venta y ambiente.", "Administrar certificados y credenciales fiscales.", "Emitir comprobantes desde ventas.", "Consultar CAE, vencimiento y resultado de autorización.", "Controlar el estado de la integración."], ["Completá los datos fiscales del comercio.", "Configurá el punto de venta correspondiente.", "Cargá y validá las credenciales requeridas.", "Realizá las pruebas en el ambiente adecuado.", "Habilitá la emisión productiva solamente después de validar."], ["Las credenciales fiscales son sensibles: restringí su administración.", "Una autorización fiscal no debe repetirse por reintentos manuales.", "Verificá tipo de comprobante y receptor antes de emitir."]) },
  { prefixes: ["/seguridad"], help: help("Seguridad", "Administrá el acceso y la protección de la cuenta.", "Permite realizar acciones de seguridad disponibles para el usuario y controlar aspectos relacionados con sus credenciales.", ["Actualizar credenciales habilitadas.", "Revisar información de la cuenta.", "Cerrar sesiones de forma segura mediante la opción Salir."], ["Ingresá a Seguridad desde Configuración.", "Elegí la acción disponible.", "Completá y confirmá los datos solicitados.", "Volvé a iniciar sesión si el sistema lo requiere."], ["No compartas contraseñas entre usuarios.", "Utilizá credenciales únicas y protegidas."]) },
  { prefixes: ["/comercio"], help: help("Mi comercio", "Mantené actualizados los datos e identidad visual del negocio.", "La información del comercio se utiliza en comprobantes, reportes, facturación y pantallas de acceso.", ["Editar razón social y datos de contacto.", "Configurar domicilio y condición fiscal.", "Incorporar el logo del comercio.", "Mantener información utilizada en documentos impresos."], ["Revisá los datos actuales.", "Actualizá la información comercial y fiscal.", "Cargá la URL del logo si corresponde.", "Guardá y verificá un reporte de ejemplo."], ["Usá un logo legible y de buena resolución.", "Los datos fiscales deben coincidir con la documentación oficial."]) },
  { prefixes: ["/notificaciones"], help: help("Notificaciones", "Consultá comunicaciones y novedades dentro del sistema.", "Reúne los avisos enviados al comercio y permite distinguir rápidamente cuáles todavía no fueron leídos.", ["Consultar notificaciones recibidas.", "Identificar mensajes pendientes.", "Marcar avisos como leídos.", "Acceder desde el indicador de la barra superior."], ["Abrí el ícono de campana.", "Seleccioná una notificación para leer su contenido.", "Revisá fecha, prioridad y alcance.", "Marcala como leída cuando corresponda."], ["Revisá periódicamente los mensajes pendientes.", "Los avisos informativos no reemplazan controles operativos del comercio."]) },
  { prefixes: ["/listados"], help: help("Listados y reportes", "Analizá la información registrada y prepará documentos para compartir.", "Los listados convierten los datos operativos en indicadores, rankings y detalles filtrables para facilitar control y toma de decisiones.", ["Reportes de clientes, proveedores y productos.", "Análisis de ventas, cantidades y ticket promedio.", "Control de cajas, movimientos y diferencias.", "Saldos de cuentas corrientes.", "Filtros por fechas y opciones de impresión."], ["Elegí el listado desde el menú lateral.", "Definí los filtros necesarios.", "Revisá indicadores y totales.", "Consultá el detalle que explica cada resultado.", "Imprimí o guardá el reporte cuando lo necesites."], ["Aplicá períodos comparables para analizar tendencias.", "Verificá los filtros activos antes de compartir un resultado."]) },
  { prefixes: ["/admin/migraciones"], help: help("Migraciones", "Trasladá datos desde Access mediante un proceso controlado.", "El módulo analiza una base heredada, valida su compatibilidad y permite migrar maestros, operaciones e historial en etapas separadas para el comercio seleccionado.", ["Analizar archivos MDB o ACCDB localmente.", "Validar tablas y columnas reconocidas.", "Simular maestros antes de insertarlos.", "Migrar historial sin modificar el stock actual.", "Revertir ejecuciones cuando las condiciones lo permiten."], ["Seleccioná el comercio de destino.", "Cargá y analizá la base Access.", "Revisá errores y advertencias de compatibilidad.", "Simulá y aplicá primero los maestros.", "Continuá con historial operativo y cierre histórico."], ["No apliques una etapa con errores.", "Confirmá siempre el comercio de destino.", "Conservá una copia del archivo original y revisá los totales simulados."]) },
  { prefixes: ["/admin"], help: help("Administración de comercios", "Gestioná comercios, accesos y módulos habilitados.", "Este espacio está reservado para la administración general de la plataforma y permite configurar cada implementación sin mezclar sus datos.", ["Crear y editar comercios.", "Asociar usuarios y accesos.", "Habilitar módulos y funciones.", "Administrar notificaciones generales.", "Acceder a las herramientas de migración."], ["Creá o seleccioná el comercio.", "Completá su información principal.", "Asociá los usuarios autorizados.", "Configurá módulos y funciones.", "Verificá el acceso utilizando un usuario del comercio."], ["Aplicá el mínimo acceso necesario.", "Revisá cuidadosamente el alcance antes de eliminar un comercio."]) },
];

const fallback = help("Ayuda del sistema", "Guía contextual de VORTEX.", "Usá el menú lateral para acceder a los módulos habilitados para tu comercio. La ayuda se adapta automáticamente a la pantalla actual.", ["Gestión comercial centralizada.", "Acceso a módulos según la configuración.", "Notificaciones y cierre de sesión desde la barra superior."], ["Elegí un módulo en el menú.", "Volvé a abrir Ayuda para consultar su guía específica."], ["Si una función no aparece, puede no estar habilitada para el comercio."]);

export function getModuleHelp(pathname: string): ModuleHelp {
  return routes
    .flatMap((route) => route.prefixes.map((prefix) => ({ prefix, help: route.help })))
    .filter(({ prefix }) => pathname === prefix || pathname.startsWith(`${prefix}/`))
    .sort((a, b) => b.prefix.length - a.prefix.length)[0]?.help ?? fallback;
}
