// Integración real en PostgreSQL temporal local. No conecta a Supabase.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFileSync, mkdtempSync, realpathSync, rmSync } from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const pgBin=process.env.PG_BIN || 'C:/Program Files/PostgreSQL/17/bin';
const tempRoot=realpathSync(os.tmpdir());
const cluster=mkdtempSync(path.join(tempRoot,'vortex-taller-test-'));
const dataDir=path.join(cluster,'data');
const server=net.createServer();
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
const port=server.address().port;
await new Promise(resolve=>server.close(resolve));
const command=(name,args,input)=>spawnSync(path.join(pgBin,name+(process.platform==='win32'?'.exe':'')),args,{input,encoding:'utf8',windowsHide:true,timeout:30000,env:{...process.env,PGCLIENTENCODING:'UTF8'},stdio:name==='pg_ctl'?'ignore':'pipe'});
const checked=result=>{if(result.error)throw result.error;if(result.status!==0)throw new Error(result.stderr || result.stdout);return result.stdout;};
const sql=input=>checked(command('psql',['-X','-qAt','-h','127.0.0.1','-p',String(port),'-U','postgres','-d','postgres','-v','ON_ERROR_STOP=1'],input));
const migration=name=>readFileSync(path.join(repo,'supabase/migrations',name),'utf8');
const tenant='10000000-0000-0000-0000-000000000001',other='10000000-0000-0000-0000-000000000002';
const user='20000000-0000-0000-0000-000000000001',operator='20000000-0000-0000-0000-000000000002';
const client='30000000-0000-0000-0000-000000000001',foreign='30000000-0000-0000-0000-000000000002';
const product='40000000-0000-0000-0000-000000000001',foreignProduct='40000000-0000-0000-0000-000000000002',variant='50000000-0000-0000-0000-000000000001';
const json=value=>`'${JSON.stringify(value).replaceAll("'","''")}'::jsonb`;
const actor=`SET app.test_user='${user}'; SET ROLE authenticated;`;
const check=(query,label)=>`SELECT test_assert((${query}), '${label}');`;
const fails=(statement,message)=>`SELECT test_error($stmt$${statement}$stmt$, '${message}');`;
let passed=0,started=false;
const test=(label,statement)=>{sql(statement);passed++;console.log('OK '+label);};
try {
  checked(command('initdb',['-D',dataDir,'-U','postgres','-A','trust','--encoding=UTF8','--no-locale']));
  checked(command('pg_ctl',['-D',dataDir,'-l',path.join(cluster,'postgres.log'),'-o',`-h 127.0.0.1 -p ${port}`,'-w','start'])); started=true;
  sql(readFileSync(path.join(repo,'scripts/fixtures/taller-schema.sql'),'utf8'));
  sql(migration('20260609150000_presupuestos.sql'));
  sql(migration('20260921170000_corregir_confirmacion_presupuesto_stock.sql'));
  sql(migration('20260916180000_ventas_desde_orden_permiten_stock_negativo.sql'));
  sql('CREATE TRIGGER stock_insert AFTER INSERT ON venta_items FOR EACH ROW EXECUTE FUNCTION apply_venta_item_stock();');
  sql(migration('20261006100000_vortex_taller.sql'));
  sql('GRANT ALL ON presupuestos,presupuesto_items,presupuesto_pagos TO authenticated;');
  sql(`INSERT INTO comercio VALUES ('${tenant}'),('${other}');
    INSERT INTO comercio_usuarios VALUES ('${tenant}','${user}','admin',true),('${tenant}','${operator}','operador',true);
    INSERT INTO comercio_parametrizacion(comercio_id,parametros) VALUES ('${tenant}','{"modulos":{"taller":true}}'),('${other}','{"modulos":{"taller":true}}');
    INSERT INTO clientes VALUES ('${client}','${tenant}','Cliente','Prueba','30545766678'),('${foreign}','${other}','Ajeno','Prueba',NULL);
    INSERT INTO proveedores VALUES ('${product}','${tenant}'),('${foreignProduct}','${other}');
    INSERT INTO productos(id,comercio_id,stock) VALUES ('${product}','${tenant}',10),('${foreignProduct}','${other}',10);
    INSERT INTO producto_variantes VALUES ('${variant}','${product}',10);
    INSERT INTO bancos VALUES ('${foreignProduct}','${other}');
    INSERT INTO tarjetas_credito VALUES ('${product}','${tenant}');`);
  const vehicleData={cliente_id:client,patente:'AB 123-CD',marca:'Renault',modelo:'Kangoo',kilometraje:1000};
  const saveVehicle=(data=vehicleData,commerce=tenant)=>`SELECT taller_guardar_catalogo('${commerce}','vehiculo',NULL,${json(data)});`;
  test('Modulo apagado no permite operar',`UPDATE comercio_parametrizacion SET parametros='{"modulos":{"taller":false}}' WHERE comercio_id='${tenant}'; ${actor} ${fails(saveVehicle(),'taller_sin_permisos')}`);
  sql(`UPDATE comercio_parametrizacion SET parametros='{"modulos":{"taller":true}}' WHERE comercio_id='${tenant}';`);
  test('Operador no puede administrar',`SET app.test_user='${operator}'; SET ROLE authenticated; ${fails(saveVehicle(),'taller_sin_permisos')}`);
  test('Cliente y comercio ajenos rechazados',actor+fails(saveVehicle({...vehicleData,cliente_id:foreign}),'taller_cliente_otro_comercio')+fails(saveVehicle(vehicleData,other),'taller_sin_permisos'));
  const vehicle=sql(actor+saveVehicle()).trim();
  test('Patente normalizada y unica',actor+check(`SELECT patente='AB123CD' FROM taller_vehiculos WHERE id='${vehicle}'`,'patente')+fails(saveVehicle(),'duplicate key'));
  test('No permite escritura directa de tablas',actor+fails(`UPDATE taller_vehiculos SET marca='Otro' WHERE id='${vehicle}'`,'permission denied'));
  const orderData={vehiculo_id:vehicle,kilometraje:1001,motivo:'Service',turno:'2026-10-10T10:00:00Z'};
  const createOrder=(data=orderData)=>`SELECT taller_guardar_orden('${tenant}',NULL,NULL,${json(data)});`;
  test('No retrocede kilometraje',actor+fails(createOrder({...orderData,kilometraje:999}),'taller_kilometraje_inferior'));
  const order=sql(actor+createOrder()).trim();
  const version=()=>Number(sql(`SELECT version FROM taller_ordenes WHERE id='${order}'`).trim());
  const service={tipo:'mano_obra',descripcion:'Service',cantidad:1.5,precio_unitario:121,porcentaje_iva:21,costo_unitario:20};
  const part={tipo:'repuesto',producto_id:product,producto_variante_id:variant,descripcion:'Filtro',cantidad:2,precio_unitario:121,porcentaje_iva:21,costo_unitario:30};
  const add=(data,ver=version())=>`SELECT taller_guardar_item('${order}',${ver},NULL,${json(data)},false);`;
  test('Rechaza producto y proveedor ajenos',actor+fails(add({...part,producto_id:foreignProduct,producto_variante_id:null}),'taller_producto_otro_comercio')+fails(add({...service,tipo:'servicio_externo',proveedor_id:foreignProduct}),'taller_proveedor_otro_comercio'));
  test('Repuesto requiere variante y cantidad entera',actor+fails(add({...part,producto_variante_id:null}),'taller_variante_requerida')+fails(add({...part,cantidad:1.5}),'check constraint'));
  test('Rechaza NaN y exceso de decimales',actor+fails(add({...service,cantidad:'NaN'}),'check constraint')+fails(add({...service,cantidad:0.00001}),'check constraint'));
  sql(actor+add(service));
  test('Detecta edicion concurrente',actor+fails(add(part,1),'taller_version_desactualizada'));
  sql(actor+add(part));
  const budget=sql(actor+`SELECT taller_generar_presupuesto('${order}',${version()});`).trim();
  test('Presupuesto con horas decimales, IVA y sin mover stock',actor+check(`SELECT total=423.5 AND subtotal=350 AND total_iva=73.5 FROM presupuestos WHERE id='${budget}'`,'totales')+check(`SELECT cantidad=1.5 FROM presupuesto_items WHERE presupuesto_id='${budget}' AND producto_id IS NULL`,'horas')+check(`SELECT stock=10 FROM producto_variantes WHERE id='${variant}'`,'stock presupuesto'));
  test('Generar presupuesto es idempotente',actor+check(`SELECT taller_generar_presupuesto('${order}',1)='${budget}'::uuid`,'idempotencia presupuesto'));
  test('Detalle aprobado protegido',actor+fails(add(service),'taller_detalle_congelado')+fails(`UPDATE presupuesto_items SET precio_unitario=1 WHERE presupuesto_id='${budget}'`,'taller_presupuesto_protegido'));
  test('No confirma antes de estar lista; revierte stock y venta',actor+fails(`SELECT confirmar_presupuesto('${budget}')`,'taller_orden_no_lista')+check('SELECT count(*)=0 FROM ventas','sin venta parcial')+check(`SELECT stock=10 FROM producto_variantes WHERE id='${variant}'`,'stock rollback'));
  const state=(next,detail='')=>`SELECT taller_cambiar_estado('${order}',${version()},'${next}','${detail}');`;
  test('Requiere aprobacion y respeta transiciones',actor+fails(state('aprobado'),'taller_motivo_requerido')+fails(state('entregado'),'taller_transicion_invalida'));
  sql(actor+state('aprobado','Aprobado en mostrador')); sql(actor+state('en_reparacion'));
  test('Requiere describir trabajo terminado',actor+fails(state('listo'),'taller_trabajo_realizado_requerido'));
  sql(actor+`SELECT taller_guardar_orden('${tenant}','${order}',${version()},${json({trabajo_realizado:'Cambio de filtro y service',turno:'',proximo_service:'2027-01-05',proximo_service_km:2000})});`);
  sql(actor+state('listo'));
  const pay=[{tipo_pago:'cta_cte',monto:423.5}];
  const invoice=(payments=pay)=>`SELECT taller_facturar_orden('${order}','factura_c',${json(payments)});`;
  test('Pagos invalidos no crean venta',actor+fails(invoice([{tipo_pago:'cta_cte',monto:1}]),'taller_pagos_no_coinciden'));
  test('Banco ajeno rechazado atomicamente',actor+fails(invoice([{tipo_pago:'transferencia',monto:423.5,banco_id:foreignProduct}]),'banco pertenece a otro comercio')+check('SELECT count(*)=0 FROM ventas','sin venta')+check(`SELECT tipo_pago='cta_cte' FROM presupuesto_pagos WHERE presupuesto_id='${budget}'`,'pago anterior intacto'));
  const sale=sql(actor+invoice()).trim();
  test('Venta integrada con stock y cuenta corriente',actor+check(`SELECT venta_id='${sale}'::uuid FROM taller_ordenes WHERE id='${order}'`,'venta vinculada')+check(`SELECT stock=8 FROM producto_variantes WHERE id='${variant}'`,'stock consumido')+check(`SELECT sum(monto)=423.5 FROM cuenta_corriente WHERE venta_id='${sale}'`,'cuenta corriente')+check(`SELECT count(*)=2 FROM venta_items WHERE venta_id='${sale}'`,'detalle'));
  test('Reintento no duplica venta, stock ni deuda',actor+check(`SELECT taller_facturar_orden('${order}','factura_c',${json(pay)})='${sale}'::uuid`,'idempotencia venta')+check('SELECT count(*)=1 FROM ventas','venta unica')+check(`SELECT stock=8 FROM producto_variantes WHERE id='${variant}'`,'stock una vez')+check('SELECT count(*)=1 FROM cuenta_corriente','deuda unica'));
  test('Detalle facturado protegido, CAE permitido',actor+fails(`UPDATE venta_items SET cantidad=3 WHERE venta_id='${sale}'`,'taller_venta_protegida')+`UPDATE ventas SET cae='86406153097333',numero_comprobante='0003-00000128',punto_venta=3,numero_secuencial=128 WHERE id='${sale}';`);
  sql(actor+state('entregado'));
  test('Entrega conserva historial y proximo servicio',actor+check(`SELECT estado='entregado' AND entregado_at IS NOT NULL AND proximo_service='2027-01-05' FROM taller_ordenes WHERE id='${order}'`,'entrega')+check(`SELECT count(*)>=6 FROM taller_orden_eventos WHERE orden_id='${order}'`,'historial'));
  test('RLS oculta datos de comercios ajenos',`SET app.test_user='${foreign}'; SET ROLE authenticated; ${check('SELECT count(*)=0 FROM taller_ordenes','RLS ordenes')}${check('SELECT count(*)=0 FROM taller_orden_items','RLS items')}`);
  test('Funciones internas y anon no expuestos',check("SELECT NOT has_function_privilege('authenticated','taller_exigir_admin(uuid)','EXECUTE')",'privada')+check("SELECT NOT has_function_privilege('anon','taller_facturar_orden(uuid,tipo_comprobante,jsonb)','EXECUTE')",'anon'));
  sql(migration('20261006110000_taller_marcas_modelos.sql'));
  sql(migration('20261006111000_taller_catalogar_vehiculos_existentes.sql'));
  test('Catalogacion conserva vehiculos y unifica nombres', actor+check(`SELECT marca_id IS NOT NULL AND modelo_id IS NOT NULL AND marca='RENAULT' AND modelo='KANGOO' FROM taller_vehiculos WHERE id='${vehicle}'`,'catalogado'));
  const brand=sql(actor+`SELECT taller_guardar_marca_modelo('${tenant}','marca','  CITROËN  ',NULL);`).trim();
  test('Marcas duplicadas por espacios, mayusculas o acentos reutilizan ID',actor+check(`SELECT taller_guardar_marca_modelo('${tenant}','marca','citroen',NULL)='${brand}'::uuid`,'marca unica'));
  const model=sql(actor+`SELECT taller_guardar_marca_modelo('${tenant}','modelo',' C3 ','${brand}');`).trim();
  test('Modelos duplicados reutilizan ID dentro de marca',actor+check(`SELECT taller_guardar_marca_modelo('${tenant}','modelo','c3','${brand}')='${model}'::uuid`,'modelo unico'));
  const anotherBrand=sql(actor+`SELECT taller_guardar_marca_modelo('${tenant}','marca','OTRA',NULL);`).trim();
  test('Mismo nombre de modelo en otra marca conserva identidad distinta',actor+check(`SELECT taller_guardar_marca_modelo('${tenant}','modelo','C3','${anotherBrand}')<>'${model}'::uuid`,'marca distinta'));
  test('Catalogos rechazan operadores y comercio ajeno',`SET app.test_user='${operator}'; SET ROLE authenticated; `+fails(`SELECT taller_guardar_marca_modelo('${tenant}','marca','NUEVA',NULL);`,'taller_sin_permisos'));
  test('Catalogos rechazan escritura directa y nombres vacios',actor+fails(`INSERT INTO taller_marcas(comercio_id,nombre) VALUES('${tenant}','NUEVA');`,'permission denied')+fails(`SELECT taller_guardar_marca_modelo('${tenant}','marca',' ',NULL);`,'taller_nombre_invalido'));
  const foreignBrand=sql(`INSERT INTO taller_marcas(comercio_id,nombre) VALUES('${other}','AJENA') RETURNING id;`).trim();
  test('Catalogos RLS oculta marcas ajenas y rechaza su modelo',actor+check(`SELECT count(*)=0 FROM taller_marcas WHERE comercio_id='${other}'`,'rls marcas')+fails(`SELECT taller_guardar_marca_modelo('${tenant}','modelo','C3','${foreignBrand}');`,'taller_marca_otro_comercio'));
  test('Vehiculo rechaza modelo de otra marca',actor+fails(saveVehicle({...vehicleData,patente:'CD234EF',marca_id:anotherBrand,modelo_id:model}),'taller_marca_modelo_inconsistente'));
  const mapped=sql(actor+saveVehicle({...vehicleData,patente:'CD234EF',marca:'Texto ignorado',modelo:'Texto ignorado',marca_id:brand,modelo_id:model})).trim();
  test('Vehiculo toma nombres canonicos desde IDs',actor+check(`SELECT marca_id='${brand}' AND modelo_id='${model}' AND modelo='C3' FROM taller_vehiculos WHERE id='${mapped}'`,'canonicos'));
  test('Formulario anterior compatible con catalogos',actor+check(`SELECT taller_guardar_catalogo('${tenant}','vehiculo','${mapped}',${json({...vehicleData,patente:'CD234EF',marca:'  renault ',modelo:' kangoo '})})='${mapped}'::uuid`,'compatibilidad')+check(`SELECT marca='RENAULT' AND modelo='KANGOO' AND marca_id IS NOT NULL AND modelo_id IS NOT NULL FROM taller_vehiculos WHERE id='${mapped}'`,'canonicos anteriores'));
  sql(migration('20261006120000_taller_vehiculo_presupuesto.sql'));
  sql(migration('20261006121000_taller_vehiculo_presupuestos_existentes.sql'));
  test('Presupuesto existente incorpora datos del vehiculo sin cambiar importes',actor+check(`SELECT taller_vehiculo->>'patente'='AB123CD' AND taller_vehiculo->>'marca'='RENAULT' AND (taller_vehiculo->>'kilometraje')::integer=1001 AND total=423.5 AND estado='confirmado' FROM presupuestos WHERE id='${budget}'`,'vehiculo presupuesto existente'));
  const anotherOrder=sql(actor+createOrder({...orderData,vehiculo_id:mapped,kilometraje:1005})).trim();
  sql(actor+`SELECT taller_guardar_item('${anotherOrder}',1,NULL,${json(service)},false);`);
  const anotherBudget=sql(actor+`SELECT taller_generar_presupuesto('${anotherOrder}',2);`).trim();
  test('Presupuesto nuevo conserva patente marca modelo y kilometraje de ingreso',actor+check(`SELECT taller_vehiculo->>'patente'='CD234EF' AND taller_vehiculo->>'modelo'='KANGOO' AND (taller_vehiculo->>'kilometraje')::integer=1005 FROM presupuestos WHERE id='${anotherBudget}'`,'vehiculo presupuesto nuevo'));
  sql(actor+`SELECT taller_guardar_catalogo('${tenant}','vehiculo','${mapped}',${json({...vehicleData,patente:'EF345GH',marca_id:brand,modelo_id:model,kilometraje:1006})});`);
  test('Cambiar vehiculo no modifica datos del presupuesto emitido',actor+check(`SELECT taller_vehiculo->>'patente'='CD234EF' AND taller_vehiculo->>'marca'='RENAULT' AND (taller_vehiculo->>'kilometraje')::integer=1005 FROM presupuestos WHERE id='${anotherBudget}'`,'datos congelados')+fails(`UPDATE presupuestos SET taller_vehiculo='{}' WHERE id='${anotherBudget}';`,'taller_presupuesto_protegido'));
  test('Proteccion del presupuesto restaurada tras reparacion',check(`SELECT tgenabled='O' FROM pg_trigger WHERE tgname='taller_presupuesto_protegido'`,'trigger activo'));
  console.log(`${passed} pruebas PostgreSQL locales correctas.`);
} finally {
  if(started)checked(command('pg_ctl',['-D',dataDir,'-m','immediate','-w','stop']));
  const resolved=path.resolve(cluster);
  assert.ok(resolved.startsWith(tempRoot+path.sep) && path.basename(resolved).startsWith('vortex-taller-test-'));
  rmSync(resolved,{recursive:true,force:true});
}
