CREATE OR REPLACE FUNCTION public.eliminar_compra_confirmada(p_compra_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE c public.compras; i public.compra_items;
BEGIN SELECT * INTO c FROM public.compras WHERE id=p_compra_id FOR UPDATE; IF NOT FOUND OR NOT public.user_belongs_to_comercio(c.comercio_id) THEN RAISE EXCEPTION 'compra_no_disponible'; END IF;
 FOR i IN SELECT * FROM public.compra_items WHERE compra_id=c.id FOR UPDATE LOOP IF (SELECT stock FROM public.productos WHERE id=i.producto_id FOR UPDATE)<i.cantidad_recibida THEN RAISE EXCEPTION 'compra_eliminacion_stock_insuficiente'; END IF; UPDATE public.productos SET stock=stock-i.cantidad_recibida WHERE id=i.producto_id AND comercio_id=c.comercio_id; END LOOP;
 DELETE FROM public.cuenta_corriente_proveedores WHERE factura_id IN(SELECT id FROM public.compras_facturas WHERE compra_id=c.id); DELETE FROM public.pagos_compra WHERE compra_id=c.id; DELETE FROM public.compras_facturas WHERE compra_id=c.id; DELETE FROM public.compras WHERE id=c.id;
END; $$;

CREATE OR REPLACE FUNCTION public.editar_compra_confirmada(p_compra_id uuid,p_proveedor_id uuid,p_fecha date,p_factura_numero text,p_fecha_vencimiento date,p_modalidad_pago text,p_porcentaje_descuento numeric,p_monto_descuento numeric,p_porcentaje_recargo numeric,p_monto_recargo numeric,p_items jsonb,p_observaciones text DEFAULT NULL)
RETURNS public.compras LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE c public.compras; f public.compras_facturas; x jsonb; p public.productos; old_items jsonb; old_qty numeric; new_qty numeric; delta numeric; base numeric:=0; final_total numeric; descuento numeric; recargo numeric; paid numeric; old_auto boolean;
BEGIN SELECT * INTO c FROM public.compras WHERE id=p_compra_id FOR UPDATE; IF NOT FOUND OR NOT public.user_belongs_to_comercio(c.comercio_id) THEN RAISE EXCEPTION 'compra_no_disponible'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.proveedores WHERE id=p_proveedor_id AND comercio_id=c.comercio_id) OR jsonb_typeof(p_items)<>'array' OR jsonb_array_length(p_items)=0 OR p_modalidad_pago NOT IN('contado','transferencia','tarjeta','cheque','cta_cte') THEN RAISE EXCEPTION 'compra_invalida'; END IF;
 SELECT * INTO f FROM public.compras_facturas WHERE compra_id=c.id FOR UPDATE; SELECT coalesce(sum(monto),0) INTO paid FROM public.cuenta_corriente_proveedores WHERE factura_id=f.id AND tipo='pago'; old_auto:=EXISTS(SELECT 1 FROM public.pagos_compra WHERE compra_id=c.id); IF paid>0 AND NOT old_auto THEN RAISE EXCEPTION 'compra_edicion_con_pagos_manuales'; END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('producto_id',producto_id,'cantidad',cantidad_recibida)),'[]'::jsonb) INTO old_items FROM public.compra_items WHERE compra_id=c.id;
 FOR x IN SELECT value FROM jsonb_array_elements(old_items) LOOP old_qty:=(x->>'cantidad')::numeric; SELECT coalesce(sum((e->>'cantidad')::numeric),0) INTO new_qty FROM jsonb_array_elements(p_items) e WHERE e->>'producto_id'=x->>'producto_id'; delta:=new_qty-old_qty; IF delta<0 AND (SELECT stock FROM public.productos WHERE id=(x->>'producto_id')::uuid FOR UPDATE)<abs(delta) THEN RAISE EXCEPTION 'compra_edicion_stock_insuficiente'; END IF; UPDATE public.productos SET stock=stock+delta::integer WHERE id=(x->>'producto_id')::uuid AND comercio_id=c.comercio_id; END LOOP;
 DELETE FROM public.compra_items WHERE compra_id=c.id;
 FOR x IN SELECT value FROM jsonb_array_elements(p_items) LOOP SELECT * INTO p FROM public.productos WHERE id=(x->>'producto_id')::uuid AND comercio_id=c.comercio_id; IF NOT FOUND OR coalesce((x->>'cantidad')::integer,0)<=0 OR coalesce((x->>'costo_unitario')::numeric,-1)<0 THEN RAISE EXCEPTION 'compra_item_invalido'; END IF; SELECT coalesce(sum((e->>'cantidad')::numeric),0) INTO old_qty FROM jsonb_array_elements(old_items) e WHERE e->>'producto_id'=x->>'producto_id'; IF old_qty=0 THEN UPDATE public.productos SET stock=stock+(x->>'cantidad')::integer WHERE id=p.id; END IF; INSERT INTO public.compra_items(comercio_id,compra_id,producto_id,descripcion,cantidad_solicitada,cantidad_recibida,costo_unitario,porcentaje_iva,actualizar_costo,subtotal,total) VALUES(c.comercio_id,c.id,p.id,p.descripcion,(x->>'cantidad')::numeric,(x->>'cantidad')::numeric,(x->>'costo_unitario')::numeric,coalesce((x->>'porcentaje_iva')::numeric,p.porcentaje_iva,0),coalesce((x->>'actualizar_costo')::boolean,true),(x->>'cantidad')::numeric*(x->>'costo_unitario')::numeric,(x->>'cantidad')::numeric*(x->>'costo_unitario')::numeric); UPDATE public.productos SET precio_costo=CASE WHEN coalesce((x->>'actualizar_costo')::boolean,true) THEN (x->>'costo_unitario')::numeric ELSE precio_costo END WHERE id=p.id; base:=base+(x->>'cantidad')::numeric*(x->>'costo_unitario')::numeric; END LOOP;
 descuento:=least(base,coalesce(p_monto_descuento,0)+base*coalesce(p_porcentaje_descuento,0)/100); recargo:=coalesce(p_monto_recargo,0)+base*coalesce(p_porcentaje_recargo,0)/100; final_total:=base-descuento+recargo;
 UPDATE public.compras SET proveedor_id=p_proveedor_id,fecha=coalesce(p_fecha,current_date),factura_numero=coalesce(nullif(trim(p_factura_numero),''),numero),fecha_vencimiento=p_fecha_vencimiento,modalidad_pago=p_modalidad_pago,subtotal=base,porcentaje_descuento=coalesce(p_porcentaje_descuento,0),monto_descuento=descuento,porcentaje_recargo=coalesce(p_porcentaje_recargo,0),monto_recargo=recargo,total=final_total,observaciones=nullif(trim(p_observaciones),'') WHERE id=c.id RETURNING * INTO c;
 UPDATE public.compras_facturas SET proveedor_id=p_proveedor_id,numero_comprobante=c.factura_numero,fecha=c.fecha,fecha_vencimiento=p_fecha_vencimiento,total=final_total WHERE id=f.id; DELETE FROM public.cuenta_corriente_proveedores WHERE factura_id=f.id; DELETE FROM public.pagos_compra WHERE compra_id=c.id; INSERT INTO public.cuenta_corriente_proveedores(comercio_id,proveedor_id,factura_id,tipo,monto,fecha,observaciones) VALUES(c.comercio_id,p_proveedor_id,f.id,'deuda',final_total,c.fecha,'Compra '||c.numero);
 IF p_modalidad_pago<>'cta_cte' THEN INSERT INTO public.cuenta_corriente_proveedores(comercio_id,proveedor_id,factura_id,tipo,monto,fecha,medio_pago,observaciones) VALUES(c.comercio_id,p_proveedor_id,f.id,'pago',final_total,c.fecha,p_modalidad_pago,'Pago de compra '||c.numero); INSERT INTO public.pagos_compra(comercio_id,compra_id,factura_id,tipo_pago,monto,fecha) VALUES(c.comercio_id,c.id,f.id,p_modalidad_pago,final_total,c.fecha); END IF; RETURN c;
END; $$;
GRANT EXECUTE ON FUNCTION public.eliminar_compra_confirmada(uuid),public.editar_compra_confirmada(uuid,uuid,date,text,date,text,numeric,numeric,numeric,numeric,jsonb,text) TO authenticated;
