// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhtqkygjvaaizbdwwsbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpodHFreWdqdmFhaXpiZHd3c2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Nzc0OTksImV4cCI6MjA3MjU1MzQ5OX0.z0cddbdYfjrpyGpN9RLtZrl8ExdFJRgSnQUEXNFl8rU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});